using System.Diagnostics;
using System.Text;

/// <summary>
/// Describes the machine the load generator is running on.
///
/// <para>
/// <b>This is not part of <see cref="RuntimeSampler"/> because it does not sample anything: it is a snapshot of the
/// client system's data written into a test file. The RuntimeSampler collects thread-pool and GC
/// counters from the server under test while this describer is called by the client
/// when it writes <c>run-info.txt</c>.</b>
/// </para>
///
/// <para>
/// The informations below are recorded because they would not be recoverable from the CSVs
/// generated by a test but they can change what a measured value means: the thread pool's
/// behavior depends on the core count, the GC counters depend on the GC mode and the offered
/// rate a machine can actually generate depends on how many cores the affinity mask gives it.
/// </para>
/// </summary>
public static class EnvironmentInfo
{
    /// <summary>
    /// Renders the environment.
    /// </summary>
    /// <param name="indent">Prefix applied to every line for nesting inside a larger report.</param>
    public static string Describe(string indent = "  ")
    {
        TimeSpan utcOffset = TimeZoneInfo.Local.GetUtcOffset(DateTime.Now);

        StringBuilder description = new StringBuilder();
        description.AppendLine($"{indent}Machine          : {Environment.MachineName}");
        description.AppendLine($"{indent}OS               : {Environment.OSVersion.VersionString}");
        description.AppendLine($"{indent}Logical CPUs     : {Environment.ProcessorCount}");
        description.AppendLine($"{indent}Runtime          : .NET {Environment.Version}");
        description.AppendLine($"{indent}Server GC        : {System.Runtime.GCSettings.IsServerGC}");

        // Every timestamp this system writes is local because logman's CSV is local and that is
        // not configurable. This line makes the absolute instant recoverable.
        description.AppendLine($"{indent}UTC offset       : {utcOffset:hh\\:mm} ({TimeZoneInfo.Local.Id})");

        // ProcessorAffinity exists only on Windows and Linux.
        if (OperatingSystem.IsWindows() || OperatingSystem.IsLinux())
        {
            try
            {
                using Process self = Process.GetCurrentProcess();
                description.AppendLine($"{indent}Process affinity : 0x{(long)self.ProcessorAffinity:X}");
            }
            catch (Exception ex)
            {
                description.AppendLine($"{indent}Process affinity : unavailable ({ex.GetType().Name})");
            }
        }

        return description.ToString();
    }
}