using Google.Protobuf;
using Grpc.Core;
using NBombedGrpcServer;

/// <summary>
/// gRPC service implementation for the <c>Operation</c> service defined in the
/// shared <c>.proto</c> file.
///
/// <para>
/// This service is intentionally stateless: no dependencies are injected and
/// no shared mutable state is accessed, so a single instance can safely serve
/// all concurrent RPCs without synchronization overhead.
/// </para>
/// </summary>
public sealed class PayloadService : Operation.OperationBase
{
    /// <summary>
    /// Handles the <c>GetPayload</c> RPC.
    ///
    /// <para>
    /// Delegates workload generation to <see cref="OperationsHandler"/>, selecting the blocking or
    /// async entry point according to <see cref="PayloadRequest.ExecutionMode"/> and the kind of
    /// work according to <see cref="PayloadRequest.WorkloadKind"/>.
    /// </para>
    /// </summary>
    /// <param name="request">
    /// The incoming RPC request containing:
    /// <list type="bullet">
    ///   <item><see cref="PayloadRequest.PayloadSize"/> response size category.</item>
    ///   <item><see cref="PayloadRequest.Intensity"/> how much work to perform.</item>
    ///   <item><see cref="PayloadRequest.WorkloadKind"/> CPU-bound or I/O-bound work.</item>
    ///   <item><see cref="PayloadRequest.ExecutionMode"/> blocking or async execution.</item>
    /// </list>
    /// </param>
    /// <param name="context">
    /// The server side call context provided by the gRPC framework. Unused: the workload is
    /// deliberately not cancellable so that a client side timeout cannot truncate the work being
    /// measured and tamper the server side counters.
    /// </param>
    /// <returns>
    /// A <c>PayloadResponse</c> whose <c>Payload</c> field carries the generated bytes.
    /// </returns>
    /// <exception cref="RpcException">
    /// Thrown with <see cref="StatusCode.InvalidArgument"/> when any parameter is out of range.
    /// </exception>
    public override async Task<PayloadResponse> GetPayload(
        PayloadRequest request,
        ServerCallContext context)
    {
        // Validate enum ranges before forwarding to OperationsHandler. Its own Validate also
        // checks these but surfacing the error as an RpcException with InvalidArgument status
        // gives the NBomber client a structured failure rather than an Internal error.
        if (!Enum.IsDefined(typeof(PayloadSize), request.PayloadSize) ||
            !Enum.IsDefined(typeof(WorkIntensity), request.Intensity) ||
            !Enum.IsDefined(typeof(WorkloadKind), request.WorkloadKind) ||
            !Enum.IsDefined(typeof(ExecutionMode), request.ExecutionMode))
        {
            throw new RpcException(new Status(
                StatusCode.InvalidArgument,
                $"Invalid parameters: PayloadSize={request.PayloadSize}, " +
                $"Intensity={request.Intensity}, WorkloadKind={request.WorkloadKind}, " +
                $"ExecutionMode={request.ExecutionMode}. All values must be in range."));
        }

        PayloadSize size = (PayloadSize)request.PayloadSize;
        WorkIntensity intensity = (WorkIntensity)request.Intensity;
        WorkloadKind kind = (WorkloadKind)request.WorkloadKind;
        ExecutionMode mode = (ExecutionMode)request.ExecutionMode;

        byte[] payloadBytes = mode == ExecutionMode.Async
            ? await OperationsHandler.ExecuteAsync(size, intensity, kind)
            : OperationsHandler.ExecuteBlocking(size, intensity, kind);

        return new PayloadResponse
        {
            // gRPC default behavior
            Payload = ByteString.CopyFrom(payloadBytes)
        };
    }
}